export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split('');

export const WHEEL_LETTERS = ["", ...ALPHABET];

export const FALLBACK_PUZZLES = [
  { word: "CAT", missingIndices: [1], hint: "A small furry pet that says meow" },
  { word: "DOG", missingIndices: [2], hint: "A loyal pet that barks" },
  { word: "SUN", missingIndices: [1], hint: "It shines in the sky during the day" },
  { word: "BUS", missingIndices: [0], hint: "A large vehicle for many people" },
  { word: "CAR", missingIndices: [2], hint: "It has four wheels and you drive it" },
  { word: "PIG", missingIndices: [1], hint: "A farm animal that says oink" },
  { word: "FOX", missingIndices: [2], hint: "A clever animal with a bushy tail" },
  { word: "BOX", missingIndices: [1], hint: "You put things inside this container" },
  { word: "HAT", missingIndices: [0], hint: "You wear this on your head" },
  { word: "JAM", missingIndices: [1], hint: "Sweet fruit spread for toast" },
  { word: "BED", missingIndices: [0], hint: "Where you sleep at night" },
  { word: "NET", missingIndices: [1], hint: "Used to catch fish or butterflies" },
  { word: "PEN", missingIndices: [1], hint: "Used to write with ink" },
  { word: "ANT", missingIndices: [2], hint: "A tiny insect that works hard" },
  { word: "BAT", missingIndices: [0], hint: "It flies at night and sleeps upside down" },
  { word: "MUG", missingIndices: [1], hint: "A large cup for hot chocolate" },
  { word: "WEB", missingIndices: [1], hint: "A spider spins this" },
  { word: "KEY", missingIndices: [0], hint: "Opens a locked door" },
  { word: "FISH", missingIndices: [2], hint: "It swims in the water" },
  { word: "DUCK", missingIndices: [1], hint: "It says quack and swims in ponds" },
  { word: "FROG", missingIndices: [2], hint: "It jumps and catches flies" },
  { word: "BALL", missingIndices: [1], hint: "You kick or throw this toy" },
  { word: "BOOK", missingIndices: [2], hint: "It has pages and you read it" },
  { word: "CAKE", missingIndices: [1], hint: "A sweet treat for birthdays" },
  { word: "TREE", missingIndices: [2], hint: "It has leaves and a trunk" },
  { word: "KITE", missingIndices: [0], hint: "You fly it in the wind" },
  { word: "MOON", missingIndices: [2], hint: "It lights up the night sky" },
  { word: "STAR", missingIndices: [1], hint: "A twinkling light in the sky" },
  { word: "MILK", missingIndices: [2], hint: "White drink from cows" },
  { word: "BIKE", missingIndices: [1], hint: "It has two wheels and pedals" },
  { word: "BIRD", missingIndices: [0], hint: "It has feathers and flies" },
  { word: "BOAT", missingIndices: [2], hint: "It floats on water" },
  { word: "CORN", missingIndices: [1], hint: "Yellow vegetable that grows on stalks" },
  { word: "DRUM", missingIndices: [2], hint: "You hit it to make music" },
  { word: "LION", missingIndices: [1], hint: "The king of the jungle" },
  { word: "BEAR", missingIndices: [2], hint: "A big furry animal that loves honey" },
  { word: "ROBOT", missingIndices: [1, 4], hint: "A machine that can walk and talk" },
  { word: "PIZZA", missingIndices: [2, 4], hint: "Round food with cheese and tomato sauce" },
  { word: "TIGER", missingIndices: [1, 3], hint: "A big cat with orange and black stripes" },
  { word: "ZEBRA", missingIndices: [1, 4], hint: "Looks like a horse with black and white stripes" },
  { word: "PANDA", missingIndices: [2, 4], hint: "Black and white bear that eats bamboo" },
  { word: "APPLE", missingIndices: [0, 3], hint: "A red or green fruit" },
  { word: "CHAIR", missingIndices: [2, 4], hint: "You sit on it" },
  { word: "HOUSE", missingIndices: [1, 4], hint: "Where people live" },
  { word: "TRAIN", missingIndices: [2, 4], hint: "It runs on tracks and says choo choo" },
  { word: "PLANE", missingIndices: [1, 4], hint: "It flies high in the sky" },
  { word: "SNAKE", missingIndices: [2, 4], hint: "A long reptile with no legs" },
  { word: "SHARK", missingIndices: [1, 4], hint: "A big fish with sharp teeth" },
  { word: "WHALE", missingIndices: [1, 4], hint: "The biggest animal in the ocean" },
  { word: "HORSE", missingIndices: [2, 4], hint: "You can ride this animal" },
  { word: "SHEEP", missingIndices: [2, 4], hint: "It has wool and says baa" },
  { word: "MOUSE", missingIndices: [1, 4], hint: "Squeaky animal that loves cheese" }
];
